# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='center',
            field=models.ForeignKey(help_text='Center', on_delete=django.db.models.deletion.CASCADE, to='base.Center'),
        ),
    ]
