# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='registration_status',
            field=models.PositiveSmallIntegerField(default=0, help_text='Registration Status'),
        ),
    ]
