# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventparticipant_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.PositiveIntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2017, help_text='year'),
        ),
    ]
