# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170910_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_age',
            field=models.PositiveIntegerField(help_text='Age Group Upper limit'),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_age',
            field=models.PositiveIntegerField(help_text='Age Group lower limit'),
        ),
    ]
