# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170913_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Event Participant Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Event Participant Updated on'),
        ),
    ]
