# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-31 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventparticipant_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True, help_text='Is event active?'),
            preserve_default=False,
        ),
    ]
