# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.PositiveIntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2018, help_text='year'),
        ),
    ]
