# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180107_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.PositiveIntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2019, help_text='year'),
        ),
    ]
