# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='is_displayed',
            field=models.BooleanField(default=True, help_text='Should the center be displayed?'),
        ),
        migrations.AddField(
            model_name='center',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Center'),
        ),
    ]
