# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 06:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170820_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=6)),
                ('min_age', models.CharField(help_text='Age Group lower limit', max_length=2, validators=[django.core.validators.RegexValidator(message='Only digits allowed.', regex='^[0-9]*$')])),
                ('max_age', models.CharField(help_text='Age Group Upper limit', max_length=2, validators=[django.core.validators.RegexValidator(message='Only digits allowed.', regex='^[0-9]*$')])),
            ],
        ),
        migrations.CreateModel(
            name='ScopedCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Center')),
                ('center_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.CenterScope')),
            ],
        ),
    ]
