# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_centerscope_scopedcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Female'), ('female', 'Male')], default='female', max_length=6),
        ),
    ]
