# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170913_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Female'), ('female', 'Male')], max_length=6),
        ),
    ]
